language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - php: 5.4
      env: PHPCS=1 DEFAULT=0

    - php: hhvm

    - php: hhvm-nightly

  fast_finish: true

  include:
    - php: 5.4
      env: PHPCS=1 DEFAULT=0

    - php: hhvm

    - php: hhvm-nightly

before_script:
  - sudo touch /usr/bin/wkhtmltopdf && sudo chmod +x /usr/bin/wkhtmltopdf
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP --ignore=vendor --ignore=tests --ignore=config . ; fi"

notifications:
  email: false
